# Copyright 2014 Lasse Dissing
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/. */
sources = []

subdirs = Split("""
renderer
system
""")

for subdir in subdirs:
    sources += map( (lambda s: '../../src/' + s) ,Glob('%s/*.cpp' % subdir, strings=True))

print (sources)
Return('sources')
